[[main]]
  name = 'FFmpeg'
  identifier = 'ffmpeg'
  url = '/ffmpeg/'
  weight = 1
  
[[main]]
  name = 'WebRTC'
  identifier = 'webrtc'
  url = '/webrtc/'
  weight = 2
  
  [[main]]
  name = 'Project'
  identifier = 'project'
  url = '/project/'
  weight = 9
  
[[main]]
  name = 'About'
  identifier = 'about'
  url = '/about/'
  weight = 99
  

